repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        args: ["."]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: make run-test
        language: system
        types: [python]

