[project]
name = "brawlstar-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.31.0",
    "pre-commit>=4.2.0",
    "pyiceberg>=0.9.1",
    "ruff>=0.12.3",
]
