default_player_tags:
  - "#G02QL2U2"
default_club_tags:
  - "80Y22P29J"
  - "2L00GJU9Y"
  - "2UQ9U9CYR"
  - "2G8G9RQR0"
  - "2LLVLVGLG"
  - "J89PL0QG"
  - "2V90RPJUR"
  - "2L298CRY2"
  - "2UG0VRPUQ"
  - "2U2YYRC9J"
  - "2GPJQU2QU"
  - "2YL2RQ9YC"
  - "2L99UUJUP"
  - "2Q0R9VJGQ"
  - "2YPJV8VCL"
  - "809LPYLJV"
  - "2RCJ99L82"
  - "2VQULYLUG"
  - "VLRYUYQ9"
  - "2VVGYPJQU"
  - "2P2GVCYP9"