# User-specific configuration overrides
# This file is NOT tracked by git and is intended for local customizations only.
# Any values here will override those in config.yaml.

default_player_tags:
  - "#PC0PPLRU"
default_club_tags:
  - "#2L00GJU9Y"